import httpx
import logging
from app.config import get_settings

settings = get_settings()
logger = logging.getLogger("app.ollama_engine")

def get_ollama_url() -> str:
    # If a specific url is set in settings, use it, otherwise fallback
    return getattr(settings, "OLLAMA_API_URL", "http://localhost:11434")

def get_ollama_model() -> str:
    # If a specific model is set in settings, use it, otherwise fallback
    # The user mentioned using llama3.2:3b in a previous project
    return getattr(settings, "OLLAMA_MODEL", "llama3.2:3b")

def analyze_data_summary(summary_text: str) -> str:
    """
    Pass the summary of data (e.g. from Pandas describe/head) to Ollama and get an analysis.
    """
    url = f"{get_ollama_url()}/api/generate"
    model = get_ollama_model()
    
    prompt = (
        "You are an expert data analyst. I am providing you with a summary of a dataset. "
        "Please provide a clear and insightful analysis of the data based on the summary statistics.\n\n"
        f"Data Summary:\n{summary_text}\n\n"
        "Analysis:"
    )
    
    payload = {
        "model": model,
        "prompt": prompt,
        "stream": False
    }

    try:
        # Increase timeout as generation might take time depending on hardware
        response = httpx.post(url, json=payload, timeout=60.0)
        response.raise_for_status()
        data = response.json()
        return data.get("response", "No response generated by Ollama.")
    except Exception as e:
        logger.exception("Failed to connect to Ollama or generate response")
        return f"Error analyzing data with Ollama: {str(e)}"
