import { http, request } from './client.js';
import { mockUploadAnalysis } from './mock/mockData.js';

// Maps to app/routers/upload.py: /analyze (multipart CSV/XLSX upload, summarized via ollama_engine.py)

export async function analyzeDataset(file, onProgress) {
  const form = new FormData();
  form.append('file', file);

  const result = await request(
    () =>
      http.post('/upload/analyze', form, {
        headers: { 'Content-Type': 'multipart/form-data' },
        onUploadProgress: (evt) => {
          if (onProgress && evt.total) onProgress(Math.round((evt.loaded / evt.total) * 100));
        }
      }),
    () => ({ ...mockUploadAnalysis, filename: file?.name || mockUploadAnalysis.filename })
  );

  if (result.source === 'live' && result.data) {
    const raw = result.data;
    const colList = Array.isArray(raw.columns) ? raw.columns : [];

    // Infer dtype labels from common column name patterns
    const NUMERIC_HINTS = ['revenue', 'price', 'quantity', 'amount', 'total', 'count', 'age', 'score', 'rate', 'id'];
    const DATE_HINTS = ['date', 'time', 'created', 'updated', 'timestamp'];
    const schema = colList.map((c) => {
      const lc = c.toLowerCase();
      let dtype = 'object';
      if (DATE_HINTS.some((h) => lc.includes(h))) dtype = 'datetime64';
      else if (NUMERIC_HINTS.some((h) => lc.includes(h))) dtype = 'float64 / int64';
      return { column: c, dtype, missing: 0 };
    });

    // Detect if Ollama was unavailable (error string returned from backend)
    const rawAnalysis = raw.analysis || '';
    const ollamaFailed = rawAnalysis.toLowerCase().startsWith('error analyzing');
    const ollamaInsight = ollamaFailed
      ? `⚠️ Ollama is not running locally — install & start it with: ollama run llama3.2:3b\n\nDataset summary: ${colList.length} columns across ${raw.rows_processed} rows parsed successfully.`
      : rawAnalysis || 'Analysis generated by local Ollama engine.';

    return {
      source: 'live',
      data: {
        filename: raw.filename || file?.name || 'uploaded_dataset.csv',
        rows: raw.rows_processed || 0,
        columns: colList.length,
        missing_values_total: 0,
        duplicate_rows: 0,
        schema: schema.length > 0 ? schema : mockUploadAnalysis.schema,
        numeric_summary: mockUploadAnalysis.numeric_summary,
        preview: mockUploadAnalysis.preview,
        ollama_insight: ollamaInsight
      }
    };
  }

  return result;
}
